---
apiVersion: v1
kind: Service
metadata:
  name: micro-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 19090
      targetPort: 9090
  selector:
    app: micro-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sidecar.istio.io/inject: "true"
  name: micro-api
spec:
  selector:
    matchLabels:
      app: micro-api
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-api
    spec:
      containers:
        - name: micro-api
          image: huiwq1990/micro-api:1.3-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 9090
