Vagrant.configure("2") do |config|
#   config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", ip: "192.168.68.111"
#     name: "vboxnet3"
  config.vm.hostname = "eapp"
  config.vm.box = "bento/centos-7.9"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end